"""empty message

Revision ID: 410d23f7b969
Revises: 4d4551a76690
Create Date: 2022-01-23 11:10:20.294583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410d23f7b969'
down_revision = '4d4551a76690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bath_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bath')
    # ### end Alembic commands ###
