"""Initial migration.

Revision ID: 4d4551a76690
Revises: 
Create Date: 2021-12-21 12:59:08.066602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4551a76690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breast_feeding_ml', sa.Integer(), nullable=True),
    sa.Column('milk_feeding_ml', sa.Integer(), nullable=True),
    sa.Column('feeding_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sick', sa.Boolean(), nullable=True),
    sa.Column('poo_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poo')
    op.drop_table('nursing')
    # ### end Alembic commands ###
